/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

import game.Game;

/**
 *
 * @author mike de groot
 */
@SuppressWarnings("serial")
public class Main_Menu extends JFrame {
	
	private JPanel ChangeUsernamePanel;
    private JPanel GamePanel;
    private JMenuItem MainMenuMenubutton;
    private JPanel MainMenuPanel;
    private JMenuItem UsernameMenubutton;
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JMenu jMenu1;
    private JMenuBar jMenuBar1;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;

	Adventure adventure;
    private static boolean OnesExecuted;
	/**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePanel = new JPanel();
        MainMenuPanel = new JPanel();
        jButton1 = new JButton();
        jLabel1 = new JLabel();
        ChangeUsernamePanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jLabel2 = new JLabel();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        MainMenuMenubutton = new JMenuItem();
        UsernameMenubutton = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);

        jButton1.setText("Start");
        jButton1.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/rsz_1textadventure_deluxe_dislplayimage.png")));

        GroupLayout MainMenuPanelLayout = new GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainMenuPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setRows(1);
        jTextArea1.setText(Game.username);
        jTextArea1.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Change your nickname!");

        GroupLayout ChangeUsernamePanelLayout = new GroupLayout(ChangeUsernamePanel);
        ChangeUsernamePanel.setLayout(ChangeUsernamePanelLayout);
        ChangeUsernamePanelLayout.setHorizontalGroup(
            ChangeUsernamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, ChangeUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChangeUsernamePanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        ChangeUsernamePanelLayout.setVerticalGroup(
            ChangeUsernamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, ChangeUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout GamePanelLayout = new GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GamePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ChangeUsernamePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addGroup(GamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GamePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ChangeUsernamePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        MainMenuPanel.getAccessibleContext().setAccessibleName("MainMenuPanel");
        ChangeUsernamePanel.getAccessibleContext().setAccessibleName("UsernamePanel");

        jMenu1.setText("Options");

        MainMenuMenubutton.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        MainMenuMenubutton.setText("Main menu");
        MainMenuMenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuMenubuttonActionPerformed(evt);
            }
        });
        jMenu1.add(MainMenuMenubutton);

        UsernameMenubutton.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        UsernameMenubutton.setText("Username");
        UsernameMenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameMenubuttonActionPerformed(evt);
            }
        });
        jMenu1.add(UsernameMenubutton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(GamePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(GamePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	if (OnesExecuted == false) {
    		OnesExecuted = true;
    		adventure = new Adventure(this);
    	}
    	if (OnesExecuted) {
    		adventure.setVisible(true);
        	this.setVisible(false);
    	}
    }

    private void UsernameMenubuttonActionPerformed(java.awt.event.ActionEvent evt) {
    	jTextArea1.setText(Game.username);
        MainMenuPanel.setVisible(false);
        ChangeUsernamePanel.setVisible(true);
    }

    private void MainMenuMenubuttonActionPerformed(java.awt.event.ActionEvent evt) {
    	Game.username = jTextArea1.getText();
        MainMenuPanel.setVisible(true);
        ChangeUsernamePanel.setVisible(false);
    }
}
